name: titan_icons
description: Flutter package containing custom icons not found in material icons to use in personal projects
version: 0.0.2
author: Madhusudhan R
homepage:

environment:
  sdk: '>=2.7.0 <3.0.0'
  # flutter: '>=1.17.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: TitanIcons
      fonts:
        - asset: fonts/titanicons.ttf
